version: '2'
services:
  nginx-proxy:
    environment:
      - MAX_BODY_SIZE=400m
    image: rysenko/nginx-proxy:latest
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro